Public ip metrics
MissionCriticalCloud/cosmic-microservices pull request #18
Opened 2017-03-15 12:36 UTC by iri989

2017-03-20 07:08 UTC, bheuvel commented on cosmic-metrics-collector/src/main/java/com/github/missioncriticalcloud/cosmic/metricscollector/repositories/PublicIPAddressMetricsRepository.java
> +/**
Suggest to remove these 'created by' comments? (Other files as well)

2017-03-20 07:11 UTC, bheuvel commented on cosmic-metrics-collector/src/main/resources/queries.yml
> +          ip.removed IS NULL
Newline missing

2017-03-20 15:28 UTC, eliasgomes requested changes
I added some remarks to this pull request. Please also properly adjust the commits and commit messages so we can easily revert and identify them, if necessary.

2017-03-20 15:28 UTC, eliasgomes commented on cosmic-metrics-collector/src/test/resources/test-schema.sql
> +) ENGINE=InnoDB AUTO_INCREMENT=50 DEFAULT CHARSET=utf8;
New line missing.

2017-03-20 15:28 UTC, eliasgomes commented on cosmic-metrics-collector/src/test/resources/test-data.sql
> +
I'd suggest to move this new test data to a new file. It keeps things easier to maintain as the test cases grow.

2017-03-20 15:28 UTC, eliasgomes commented on cosmic-metrics-collector/src/main/java/com/github/missioncriticalcloud/cosmic/metricscollector/repositories/jdbc/PublicIPAddressMetricsJdbcRepository.java
> +public class PublicIPAddressMetricsJdbcRepository implements PublicIPAddressMetricsRepository {
I suggest to use the _spring-like_ camel-case for names wherever it applies. For example: `PublicIpAddressMetricsJdbcRepository`.

2017-03-20 15:28 UTC, eliasgomes commented on cosmic-metrics-collector/src/main/java/com/github/missioncriticalcloud/cosmic/metricscollector/tasks/PublicIPAddressMetricCollector.java
> +public class PublicIPAddressMetricCollector implements MetricCollector{
Please add a space between `MetricCollector` and `{` for better reading of the code.

2017-03-20 15:44 UTC, eliasgomes requested changes

2017-03-20 15:44 UTC, eliasgomes commented on cosmic-metrics-collector/src/main/resources/queries.yml
> +    SELECT
We should filter by `state` as well. If there's a problem while the public IP address is being allocated (with `Allocating` state), we shouldn't bill that IP. So, please add to the `WHERE` clause: `ip.state = 'Allocated'`

2017-03-29 11:27 UTC, eliasgomes approved these changes

2017-03-29 11:30 UTC, merged