Implement sorting functionality for table headers
MissionCriticalCloud/cosmic-microservices pull request #37
Opened 2017-04-13 14:38 UTC by borisroman

We can now sort by clicking a table header! Default is ASC by DOMAIN_PATH

2017-04-13 15:20 UTC, bheuvel reviewed
FWIW LGTM 😄

2017-04-13 15:31 UTC, eliasgomes requested changes

2017-04-13 15:31 UTC, eliasgomes commented on cosmic-usage-ui/src/main/resources/public/app/main.js
> +    domainsTableDomainHeadId: '#ui-domains-table-domain-head',
These are all IDs, I would suggest to remove the `Id` part of the name of these attributes.

2017-04-13 15:31 UTC, eliasgomes commented on cosmic-usage-ui/src/main/resources/public/app/main.js
> +    domainTableHeaderState: 'data-state',
Combined with `jQuery.data(...)` we can eliminate the `data-` part of the string.

2017-04-13 15:31 UTC, eliasgomes commented on cosmic-usage-ui/src/main/resources/public/app/main.js
> +            that.flipSortingSign($(this), 'DESC');
Please create constants out of strings like this (`DESC`, `ASC`, `&#9660`, `&#9650`).

2017-04-13 15:31 UTC, eliasgomes commented on cosmic-usage-ui/src/main/resources/public/app/main.js
> +        switch(state) {
Please add a space between `switch` and `(`.

2017-04-13 15:31 UTC, eliasgomes commented on cosmic-usage-ui/src/main/resources/public/app/main.js
> +                $(e).html($(e).attr(this.domainTableHeaderLabel) + "&#9660");
We don't need string interpolation (double-quotes) for these strings.

2017-04-13 15:31 UTC, eliasgomes commented on cosmic-usage-ui/src/main/resources/public/app/main.js
> +                console.error("ERRR! Wrong state.")
Unnecessary string interpolation.

2017-04-13 15:31 UTC, eliasgomes commented on cosmic-usage-ui/src/main/resources/public/app/main.js
> +        $( this.tableHeaderSortable ).each(function() {
Please remove the spaces around `this.tableHeaderSortable` for consistency.

2017-04-13 15:31 UTC, eliasgomes commented on cosmic-usage-ui/src/main/resources/public/app/main.js
> +        return [sortBy, sortOrder];
Returning an object would help with reading these values later on. Something like:
```
return {
  sortBy: sortBy,
  sortOrder: sortOrder
};
```

2017-04-13 15:31 UTC, eliasgomes commented on cosmic-usage-ui/src/main/resources/public/app/main.js
> +        $( this.tableHeaderSortable ).each(function() {
Please remove the spaces around this.tableHeaderSortable for consistency.

2017-04-13 15:31 UTC, eliasgomes commented on cosmic-usage-ui/src/main/resources/public/app/main.js
> +        this.generateSortableReport(currentSorting[0], currentSorting[1]);
Turning `currentSorting` into an object you could read its values with something like `currentSorting.sortBy` and `currentSorting.sortOrder`.

2017-04-13 15:31 UTC, eliasgomes commented on cosmic-usage-ui/src/main/resources/public/app/main.js
> +            sortBy = 'DOMAIN_PATH';
Please create constants out of these strings.

2017-04-13 15:31 UTC, eliasgomes commented on cosmic-usage-ui/src/main/resources/public/app/main.js
> +            if ($(this).attr(that.domainTableHeaderState) in { ASC: '', DESC: '' }) {
Please use something like: http://underscorejs.org/#contains

2017-04-13 16:22 UTC, borisroman commented
@eliasgomes Fixed all your comments!

2017-04-14 08:15 UTC, eliasgomes requested changes

2017-04-14 08:15 UTC, eliasgomes commented on cosmic-usage-ui/src/main/resources/public/app/main.js
> +        var currentSorting = this.getCurrentSorting()
Even though the semi-column is optional (at the end of the line), we should use it IMO :)

2017-04-14 08:15 UTC, eliasgomes commented on cosmic-usage-ui/src/main/resources/public/app/main.js
> +        if (currentSorting.sortBy === '' && currentSorting.sortOrder === '') {
I'd move this logic to the `getCurrentSorting` method and I'd write `currentSorting.sortBy = this.DEFAULT_SORT_BY;` and `currentSorting.sortOrder = this.DEFAULT_SORT_ORDER;`

2017-04-14 08:15 UTC, eliasgomes commented on cosmic-usage-ui/src/main/resources/public/app/main.js
> +            if(_.contains([that.ASCENDING, that.DESCENDING], $(this).data(that.domainTableHeaderDataState))) {
A little space between `if` and `(` ?

2017-04-14 08:15 UTC, eliasgomes commented on cosmic-usage-ui/src/main/resources/public/app/main.js
> +    flipSortingSign: function(e, state) {
I'd rename `e` to `column` or `header`.

2017-04-14 08:15 UTC, eliasgomes commented on cosmic-usage-ui/src/main/resources/public/app/main.js
> +        var currState = $(e.target).data(this.domainTableHeaderDataState);
I'd give `$(e.target)` a name since it's used twice and would help knowing what it is: `const header = $(e.target)`.

2017-04-14 08:15 UTC, eliasgomes commented on cosmic-usage-ui/src/main/resources/views/index.html
> +                                <th data-state="" data-label="Domain" data-sortby="DOMAIN_PATH" class="text-uppercase table-header-sortable"></th>
If they're empty (`data-state`), they don't have to be defined.

2017-04-18 04:56 UTC, borisroman commented
@eliasgomes More comments? I've got my Webstorm running... 👍

2017-04-18 07:49 UTC, eliasgomes approved these changes

2017-04-18 07:49 UTC, merged