Added Resources jdbc repositories tests
MissionCriticalCloud/cosmic-microservices pull request #54
Opened 2017-04-24 12:18 UTC by iri989

2017-05-08 13:04 UTC, eliasgomes requested changes

2017-05-08 13:04 UTC, eliasgomes commented on cosmic-usage-api/src/test/resources/test-public-ips-repository-data.sql
> +INSERT INTO `domain`
I'd suggest renaming this file to `public-ips-repository-test-data.sql` and doing the same with other similar files like `test-domains-repository-data.sql`, `test-virtual-machines-repository-data.sql`, etc.

2017-05-08 13:04 UTC, eliasgomes commented on cosmic-usage-api/src/test/java/com/github/missioncriticalcloud/cosmic/api/usage/repositories/jdbc/ResourcesJdbcRepositoryIT.java
> +public class ResourcesJdbcRepositoryIT {
I'd suggest having individual tests for each repository. That means splitting `ResourcesJdbcRepositoryIT` into `VirtualMachinesJdbcRepositoryIT`, `VolumesJdbcRepositoryIT`, etc.

2017-05-29 15:30 UTC, borisroman commented
go build

2017-05-29 15:34 UTC, borisroman commented
go build

2017-05-29 20:45 UTC, eliasgomes commented on cosmic-usage-api/src/test/java/com/github/missioncriticalcloud/cosmic/api/usage/repositories/jdbc/PublicIpsJdbcRepositoryIT.java
> +    private PublicIpsJdbcRepository publicIpsRepository;
We shouldn't lock the test to any specific implementation of a repository, JDBC in this case. I would suggest instead to point to the repository's interface (`PublicIpsRepository`), rename the test class to `PublicIpsRepositoryIT` and move the class one package up.

2017-05-29 20:45 UTC, eliasgomes commented on cosmic-usage-api/src/test/java/com/github/missioncriticalcloud/cosmic/api/usage/repositories/jdbc/VirtualMachinesJdbcRepositoryIT.java
> +    private VirtualMachinesJdbcRepository virtualMachinesRepository;
Please see my comment in `PublicIpsJdbcRepositoryIT.java`

2017-05-29 20:45 UTC, eliasgomes commented on cosmic-usage-api/src/test/java/com/github/missioncriticalcloud/cosmic/api/usage/repositories/jdbc/VolumesJdbcRepositoryIT.java
> +    private VolumesJdbcRepository volumesRepository;
Please see my comment in `PublicIpsJdbcRepositoryIT.java`

2017-05-29 22:16 UTC, iri989 commented on cosmic-usage-api/src/test/java/com/github/missioncriticalcloud/cosmic/api/usage/repositories/jdbc/PublicIpsJdbcRepositoryIT.java
> +    private PublicIpsJdbcRepository publicIpsRepository;
Done! Thanks :)

2017-07-11 13:25 UTC, eliasgomes approved these changes

2017-07-11 13:25 UTC, merged